apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}--redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          args: ["--requirepass", "{{ .Values.redis.password }}"]
          volumeMounts:
            - name: redis-storage
              mountPath: /data
        
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}--redis-pvc