apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--python-api
spec:
  selector: 
    app: {{ .Release.Name }}--python-api
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      