replicaCount: 1

image:
  repository: python-api
  tag: latest
  pullPolicy: Never
  containerPort: 8000

service:
  port: 80

redis:
  password: "redis-123"
  storage: standard

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /api
