apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/redis-k8s-lab.git
    targetRevision: Head
    path: fastapi-redis
    helm:
      valueFiles:
        - ../values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true